### ISSUE TITLE
How to use URL hyperlinks for timeline events?

### ISSUE THREAD

**Issue by SeaDude** [GjjvdBurg/labella.py#19]
Hello!

Starting to get acquainted with the tool. Its nice! Thank you.

- **Where should I add hyperlinks for timeline events?**
    - I tried adding them to the `items` array, like this, but no-go:
```
items = [
    {
         "time": date(1986, 1, 1), 
         "text": "\\href{http://www.overleaf.com}{Something Linky}"
     },
     {
         "time": date(1991, 1, 1),
         "text": "\\href{http://www.overleaf.com}{Something Linky}",
    }
]
```
- Also tried adding it under `options` to the `textfn` lambda. But that didn't work.
- Ideally I need the href to be usable in the PDF output
- **Please give an example using `timeline_kit_1.py` if possible.**

**Comment by GjjvdBurg** [comment]
Here's the patch for `timeline_kit_1.py`:

```diff
diff --git a/examples/timeline_kit_1.py b/examples/timeline_kit_1.py
index 8ebf35f..8efd591 100644
--- a/examples/timeline_kit_1.py
+++ b/examples/timeline_kit_1.py
@@ -14,7 +14,7 @@ def main():
         {
             "time": date(1980, 4, 17),
             "episode": 5,
-            "text": "The Empire Strikes Back",
+            "text": "\\href{https://gertjan.dev}{gertjan.dev}",
         },
         {
             "time": date(1984, 4, 25),
@@ -56,7 +56,11 @@ def main():
         "labella": {
             "nodeHeight": 12,
         },
-        "latex": {"fontsize": "12pt", "reproducible": True},
+        "latex": {
+            "fontsize": "12pt",
+            "reproducible": True,
+            "preamble": "\\usepackage[hidelinks]{hyperref}",
+        },
     }
 
     tl = TimelineSVG(items, options=options)
```

This will only work for the PDF output, so disable `TimelineSVG` when testing.

**Comment by SeaDude** [comment]
Hm...

**I'm getting:**
```
Traceback (most recent call last):
  File "E:\dataDocuments\python\timeline_test\timeline.py", line 151, in <module>
    main()
  File "E:\dataDocuments\python\timeline_test\timeline.py", line 145, in main
    tl.export("timeline_kit_1.tex")
  File "E:\dataDocuments\python\timeline_test\.venv\lib\site-packages\labella\timeline.py", line 512, in 
export
    self.nodes, self.renderer = self.compute()
  File "E:\dataDocuments\python\timeline_test\.venv\lib\site-packages\labella\timeline.py", line 243, in 
compute
    nodes = self.get_nodes()
  File "E:\dataDocuments\python\timeline_test\.venv\lib\site-packages\labella\timeline.py", line 222, in 
get_nodes
    n = Node(self.timePos(it.data), it.width, data=it)
  File "E:\dataDocuments\python\timeline_test\.venv\lib\site-packages\labella\timeline.py", line 304, in 
timePos
    return self.options["scale"](self.options["timeFn"](thedict))
  File "E:\dataDocuments\python\timeline_test\.venv\lib\site-packages\labella\scale.py", line 507, in __call__
    return self._linear(dt2milli(x))
  File "E:\dataDocuments\python\timeline_test\.venv\lib\site-packages\labella\scale.py", line 380, in __call__
    return self._output(x)
  File "E:\dataDocuments\python\timeline_test\.venv\lib\site-packages\labella\scale.py", line 31, in <lambda>
    return lambda x: i(u(x))
  File "E:\dataDocuments\python\timeline_test\.venv\lib\site-packages\labella\scale.py", line 35, in <lambda>
    return lambda x: (x - a) / (b - a)
ZeroDivisionError: float division by zero
```

**When using:**

```python
from datetime import date
from labella.timeline import TimelineTex

def main():
    items = [
        {
            "time": date(2021, 4, 1),
            "text": "\\href{https://gertjan.dev}{gertjan.dev}"
        }
    ]

    options = {
        "margin": {"left": 70, "right": 20, "top": 20, "bottom": 20},
        "initialWidth": 1300,
        "initialHeight": 1600,
        "direction": "right",
        "dotColor": "#000000",
        "labelBgColor": "#000000",
        "linkColor": "#000000",
        "textFn": lambda x: "{\LARGE %s -- %s}" % (x["time"].date(), x["text"]),
        "labelPadding": {"left": 2, "right": 0, "top": 2, "bottom": 0},
        "labella": {
            "nodeHeight": 12,
        },
        "latex": {
            "fontsize": "12pt",
            "reproducible": True,
            "preamble": "\\usepackage[hidelinks]{hyperref}",
        }
    }

    tl = TimelineTex(items, options=options)
    tl.export("timeline_kit_1.tex")

if __name__ == "__main__":
    main()
```

**Comment by GjjvdBurg** [comment]
That's due to having only one label, try it with more than one and it'll work.

**Comment by SeaDude** [comment]
You got it! Adding a second node did the trick!

Thank you so much for all the support! Cool project!
