### ISSUE TITLE
latexmk issue

### ISSUE THREAD

**Issue by AstronautFireman** [GjjvdBurg/labella.py#3]
Hey there, never used laTex before, but I've installed it with homebrew on OS X. Running Python 3.6 

Getting this error:

FileNotFoundError: [Errno 2] No such file or directory: 'latexmk': 'latexmk'

when trying to run the examples provided.

**Comment by AstronautFireman** [comment]
Getting this error: 

`FileNotFoundError: [Errno 2] No such file or directory: 'latexmk': 'latexmk'`

when trying to run the examples provided.

**Comment by GjjvdBurg** [comment]
It seems like latexmk can't be found by the python subprocess. If you open
a terminal and type "latexmk" (without quotes), does it work? Or does this
give the same error? If it doesn't work, you should try adding the
directory with the latexmk executable to your PATH variable.

Hope this helps!

On 6 Jan 2018 05:58, "AstronautFireman" <notifications@github.com> wrote:

I've updated latexmk through TeX live and verified that it is working
through terminal. Here's the expanded error. Is this just not compatible
with MacTex perhaps?

runfile('/Users/XXXX/Desktop/untitled1.py', wdir='/Users/XXXX/Desktop')
Traceback (most recent call last):

  File "<ipython-input-5-d407a6b555e6>", line 1, in <module>
    runfile('/Users/XXXX/Desktop/untitled1.py', wdir='/Users/XXXX/Desktop')

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py",
line 710, in runfile
    execfile(filename, namespace)

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py",
line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/XXXX/Desktop/untitled1.py", line 62, in <module>
    main()

  File "/Users/XXXX/Desktop/untitled1.py", line 59, in main
    tl = TimelineSVG(items, options=options)

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/labella/timeline.py",
line 261, in __init__
    super().__init__(items, options=options, output_mode='svg')

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/labella/timeline.py",
line 116, in __init__
    self.items = self.parse_items(dicts, output_mode=output_mode)

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/labella/timeline.py",
line 152, in parse_items
    tex_preamble=self.options['latex']['preamble'])

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/labella/timeline.py",
line 78, in __init__
    self.width, self.height = self.get_text_dimensions()

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/labella/timeline.py",
line 84, in get_text_dimensions
    width, height = text_dimensions(self.text, fontsize='12pt')

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/labella/tex.py",
line 109, in text_dimensions
    width, height = get_latex_dims(tex, silent=silent)

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/labella/tex.py",
line 79, in get_latex_dims
    compile_latex(fname, tmpdirname, silent=silent)

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/labella/tex.py",
line 64, in compile_latex
    raise(e)

  File "/Users/XXXX/anaconda3/lib/python3.6/site-packages/labella/tex.py",
line 62, in compile_latex
    output = subprocess.check_output(command, stderr=subprocess.STDOUT)

  File "/Users/XXXX/anaconda3/lib/python3.6/subprocess.py", line 336,
in check_output
    **kwargs).stdout

  File "/Users/XXXX/anaconda3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:

  File "/Users/XXXX/anaconda3/lib/python3.6/subprocess.py", line 709,
in __init__
    restore_signals, start_new_session)

  File "/Users/XXXX/anaconda3/lib/python3.6/subprocess.py", line 1344,
in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'latexmk': 'latexmk'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GjjvdBurg/labella.py/issues/3#issuecomment-355721096>,
or mute the thread

**Comment by adeoy** [comment]
Install "latexmk" on your LaTeX compiler. Open your package manager on Mac and search for "latexmk", once installed that should solve the issue.

**Comment by GjjvdBurg** [comment]
Closing due to inactivity.
